-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "FrierenBLZ")
hl.env("XCURSOR_SIZE", "49")

-- Settings
hl.config({
    cursor = {
        no_hardware_cursors = 1,
    },
    general = {
        allow_tearing = true,
        col = {
            active_border = "0xffc1948b",
            inactive_border = "0xff2b2121",
        },
        gaps_in = 8,
        gaps_out = 20,
        resize_on_border = true,
    },
    misc = {
        animate_manual_resizes = true,
        animate_mouse_windowdragging = false,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        focus_on_activate = true,
        vrr = 3,
    },
    xwayland = {
        force_zero_scaling = true,
    },
})

-- Bezier curves
hl.curve("custom1", { type = "bezier", points = { {0.142, 0.526}, {0.321, 0.894} } })
hl.curve("custom2", { type = "bezier", points = { {1.0, 0.253}, {0.321, 0.894} } })
hl.curve("easeOutQuint", { type = "bezier", points = { {0.23, 1.0}, {0.32, 1.0} } })

-- Animations
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})
hl.animation({
    leaf = "workspacesIn",
    enabled = true,
    speed = 1.21,
    bezier = "easeOutQuint",
    style = "slidefade",
})
hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = 1.94,
    bezier = "easeOutQuint",
    style = "slidefade",
})
hl.animation({
    leaf = "specialWorkspace",
    enabled = true,
    speed = 1.4,
    bezier = "custom1",
    style = "slidefadevert",
})
hl.animation({
    leaf = "specialWorkspaceOut",
    enabled = true,
    speed = 1.4,
    bezier = "custom2",
    style = "slidefadevert",
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1920x1080@144.00Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})

-- Workspaces
hl.workspace_rule({
    workspace = "1",
    persistent = true,
})

-- Keybinds
hl.unbind("SUPER + T")
hl.bind("SUPER + T", hl.dsp.exec_cmd("kitty"))
hl.unbind("SUPER + Q")
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.unbind("SUPER + R")
hl.bind("SUPER + R", hl.dsp.exec_cmd("vicinae toggle"))
hl.unbind("SUPER + F")
hl.bind("SUPER + F", hl.dsp.window.float({ action = "toggle" }))
hl.unbind("CTRL + Print")
hl.bind("CTRL + Print", hl.dsp.exec_cmd("grim -g \"$(slurp -d)\" - | wl-copy"))
hl.unbind("CTRL + O")
hl.bind("CTRL + O", hl.dsp.exec_cmd("audiosource run"))

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("vicinae server --replace")
    hl.exec_cmd("noctalia --daemon")
    hl.exec_cmd("/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=gpu-screen-recorder-gtk com.dec05eba.gpu_screen_recorder")
    hl.exec_cmd("clipse -listen")
end)
